### ISSUE TITLE
Formating is not rest after color char

### ISSUE THREAD

**Issue by Paulomart** [FoxInFlame/MinecraftColorCodes#1]
If you have the following color code:
```
§aHello§lTest§fWorld
```
World is being renders bold.

**Comment by FoxInFlame** [comment]
"World" would be rendered bold in Minecraft as well. Formatting codes
stay there when you change the text's color.

When you add $l, $n, $m, $k or $o, all of them add up to each other,
and all will be active at once, unless $r is used. The colors are a
completely different thing, and when the colors change, the formatting
will not.

**Comment by Paulomart** [comment]
See: http://wiki.vg/Chat#Styles

> Using any color codes will reset the current style back to plain (unknown if this is a bug or intended behavior).

**Comment by FoxInFlame** [comment]
Looks like my mistake. I looked around, and found out that even the Minecraft Gamepedia is writing what you said. I'll try to fix this.

http://minecraft.gamepedia.com/Formatting_codes

> If a color code is used after a formatting code, the formatting code will be disabled beyond the color code point. For example, §cX§nY displays as XY, whereas §nX§cY displays as XY. Therefore, when using a color code in tandem with a formatting code, ensure the color code is used first and reuse the formatting code when changing colors.

**Comment by FoxInFlame** [comment]
MinecraftColorCodes has been updated to 3.7 with your mentioned changes included. There is some huge changes in this, be sure to read the ReadME.

**Comment by Paulomart** [comment]
Thanks :)

**Comment by Paulomart** [comment]
Quick tip: You dont need to create the oldFiles folder, use a git tag

**Comment by FoxInFlame** [comment]
But I like to keep it that way. I don't really get used to GitHub, nor do I intend to.
